# Generated by Django 5.2.4 on 2025-07-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('part time', 'part time')], max_length=25)),
                ('description', models.CharField(max_length=400)),
                ('published_at', models.DateField(auto_now=True)),
                ('salary', models.IntegerField(default=0, max_length=20)),
                ('experience', models.IntegerField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
    ]
