# Generated by Django 5.2.4 on 2025-07-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
